### ISSUE TITLE
Add Ruby Buildpack to Full Builder

### ISSUE THREAD

**Issue by kvedurmu** [paketo-buildpacks/full-builder#14]
Once the Ruby Buildpack has been promoted to an official Paketo Buildpack, we should add it to the **Paketo Full Builder** so that users can easily consume the buildpack.

**Comment by genevieve** [comment]
This would be great! I thought I could leave off specifying the ruby buildpack when using the full builder but it failed. This was the error message (without using the pack `--verbose` flag):
```
===> DETECTING
======== Output: paketo-buildpacks/go-mod-vendor@0.0.166 ========
failed to parse go.mod: open /workspace/go.mod: no such file or directory
err:  paketo-buildpacks/go-mod-vendor@0.0.166 (1)
ERROR: No buildpack groups passed detection.
ERROR: failed to detect: buildpack(s) failed with err
ERROR: failed to build: executing lifecycle: failed with status code: 101
```

**Comment by floragj** [comment]
Check out the latest release of the builder for ruby support :)
