### ISSUE TITLE
Start publishing versioned full builder releases to GCR

### ISSUE THREAD

**Issue by kvedurmu** [paketo-buildpacks/full-builder#16]
**Context**
Once we finish up the changes proposed in https://github.com/paketo-buildpacks/builder/issues/27, we should start publishing (tagging) each version of the **Full** Builder. This will allow users to `pack build` apps using a specific version of the builder, and eventually allow us to publish Github releases and release notes. 

**Proposal**
We should tag each Full Builder release with as follows `gcr.io/paketo-buildpacks/builder-tmp:<VERSION>-full`

Initial versioning should be `0.1.0` and bump the patch version whenever the builder changes. This will eventually allow us to get rid of the concourse jobs that currently publish builders and ensure a smooth transition for users.

**Comment by floragj** [comment]
Do we still intend to publish the full builder to both GCR and Dockerhub? [This issue](https://github.com/paketo-buildpacks/base-builder/issues/5) seems to imply that only the base builder will be published to GCR as well.

**Comment by genevieve** [comment]
Yes, for consistency, it would be great if the tiny, base, and full builders were published to GCR. When I defaulted to the base builder and saw the path (gcr.io/paketo-buildpacks/builder:base), I expected to similarly be able to use `gcr.io/paketo-buildpacks/builder:tiny` (which works) and `gcr.io/paketo-buildpacks/builder:full` (which doesnt).

**Comment by kvedurmu** [comment]
I believe the intention of this issue is to make sure we continue to publish builders with a version tag. It's just getting published to a temporary path on GCR for now because we'd like to verify that everything looks good before publishing to the official Dockerhub paths (due to the lift and shift from concourse to github actions). 

There are some reasons why Full isn't getting published to GCR. I'll open up that other issue and comment there.

**Comment by kvedurmu** [comment]
This looks great. I cut a new release of the Paketo Node.js Buildpack and the GHA created a PR with the updated buildpack, tested the new builder, merged it, and created a new patch release of the builder. I'm able to run `pack inspect-builder gcr.io/paketo-buildpacks/builder-tmp:0.1.2-full` and can see the updated buildpack in the builder.
