### ISSUE TITLE
The full builder is not available on gcr.

### ISSUE THREAD

**Issue by genevieve** [paketo-buildpacks/full-builder#21]
When I try pulling the full builder instead of the base with `--builder gcr.io/paketo-buildpacks/builder:full`, I get:
```
ERROR: failed to build: failed to fetch builder image 'gcr.io/paketo-buildpacks/builder:full': image gcr.io/paketo-buildpacks/builder:full does not exist on the daemon: not found
```

When I try pulling from dockerhub with `--builder paketobuildpacks/builder:full`, it works.

Is there a different tag for pulling the full builder from gcr?

**Comment by floragj** [comment]
Hi there. We don't currently distribute the full builder on GCR. Check out [this issue](https://github.com/paketo-buildpacks/full-builder/issues/16) for conversation around whether we plan to in the future. 

Is there a particular reason you'd prefer to pull from GCR and not dockerhub? And did you run across documentation somewhere that indicated the full builder was available on GCR?

**Comment by genevieve** [comment]
Hey! When I was looking at the output of a pack build run, I saw that it was pulling `gcr.io/paketo-buildpacks/builder:base`. When I was able to use the tiny builder for a go app, I just subbed `tiny` for `base` and was able to pull from gcr. When I was building a nodejs & ruby application and needed the full builder, I expected to be able to do the same (subbing full for base and pulling from gcr.) No preference of GCR over dockerhub, mostly an expectation based on the behavior of the other builders. I can close this issue if there's another one open related.

**Comment by floragj** [comment]
Thanks for the explanation. I'll go ahead and close this out. Feel free to weigh in on the linked issue above if you think not pushing the builder to GCR creates a confusing user experience!

**Comment by kvedurmu** [comment]
We're ultimately intending to only publish the builders to Dockerhub. This is largely for cost reasons (we didn't realize how expensive GCR would be when we initially launched the project). The builders that you see on the [Paketo website](https://paketo.io/docs/builders/) or by running `pack suggest-builders` are the ones that we recommend to users. Since the Full builder was introduced pretty recently, we decided to only publish this to Dockerhub. We need to continue publishing the Base builder to GCR for backwards compatibility reasons for Spring Boot users. See https://github.com/spring-projects/spring-boot/issues/23152 for more details.

**Comment by kvedurmu** [comment]
hey @genevieve, where did you see pack build output pulling from GCR? If it's somewhere on the website, we definitely want to get this updated to use Dockerhub 🙂

**Comment by genevieve** [comment]
Oh great! It's helpful to know the long term plan is to move to dockerhub. I'll make sure we point to that from now on.

```
$ pack build app-name
base: Pulling from paketo-buildpacks/builder
Digest: sha256:828606284632841f7ebd2a9687c1cfc23835b50ea52f71d00386097502cbedfb
Status: Image is up to date for gcr.io/paketo-buildpacks/builder:base
...
```

**Comment by kvedurmu** [comment]
It's likely that `gcr.io/paketo-buildpacks/builder:base` is currently set as your default builder. Running `pack inspect-builder` with no args would confirm that

**Comment by genevieve** [comment]
You are correct!
```
$ pack inspect-builder
Inspecting default builder: gcr.io/paketo-buildpacks/builder:base
```

I don't recall setting it as my default. Is that something the pack cli does or something I forgot I did? 😅

**Comment by kvedurmu** [comment]
The Pack suggested builders were the GCR ones up until a month ago, so it's likely that you set it to GCR ones a while back 🙂
