### ISSUE TITLE
Docker image has too many layers

### ISSUE THREAD

**Issue by cborealis** [paketo-buildpacks/full-builder#213]
When building a project that adds several buildpacks, the build fails with 'max depth exceeded'

To reproduce:
` pack build --builder paketobuildpacks/builder:full --buildpack gcr.io/paketo-buildpacks/java someproject`

```
full: Pulling from paketobuildpacks/builder
Digest: sha256:dd424d44638dffa73acd684717ec2a545fd5b9f8487ae056b504f5a950c11f00
Status: Image is up to date for paketobuildpacks/builder:full
full-cnb: Pulling from paketobuildpacks/run
Digest: sha256:5da6f3cb8d1b4fce1945b1a519496086e575b1ad4215780c67e27835d43c04d3
Status: Image is up to date for paketobuildpacks/run:full-cnb
latest: Pulling from paketo-buildpacks/java
Digest: sha256:a286099073e604bfaa0de75aba63aef035a5e67581f9e5294082be6ccaf034d5
Status: Image is up to date for gcr.io/paketo-buildpacks/java:latest
ERROR: failed to build: failed to write image to the following tags: [pack.local/builder/7a6d6b75757679616571:latest: image load 'pack.local/builder/7a6d6b75757679616571:latest'. first error: embedded daemon response: max depth exceeded]
```

It looks like the docker image alredy has 107 layers, which is dangerously near to the 125 maximum:
`docker history paketobuildpacks/builder:full | wc -l`
107

## Build Configuration
pack version 0.18.0
docker 20.10.5

**Comment by arjun024** [comment]
@cborealis This is a known bug with the `pack` platform which is used to create the [full-builder image](https://github.com/paketo-buildpacks/full-builder/blob/v0.1.126/.github/workflows/push-image.yml#L36). This should be resolved once pack is released with https://github.com/buildpacks/pack/issues/1081 fixed and a version released.

**Comment by cborealis** [comment]
Thank you for the fast answer. I built pack from sources, and can confirm that it now works locally.
