### ISSUE TITLE
Full Builder Created By Version

### ISSUE THREAD

**Issue by kvedurmu** [paketo-buildpacks/full-builder#25]
When I run `pack inspect-builder gcr.io/paketo-buildpacks/builder-tmp:full` the Created By section has some interpolated Pack version. I think that this should be the actual version of pack that was used to create the builder.

```
pack inspect-builder gcr.io/paketo-buildpacks/builder-tmp:full
Inspecting builder: gcr.io/paketo-buildpacks/builder-tmp:full

REMOTE:

Description: Ubuntu bionic base image with buildpacks for Java, .NET, NodeJS, Golang, PHP, HTTPD and NGINX

Created By:
  Name: Pack CLI
  Version: #{PACK_VERSION}#
```

**Comment by floragj** [comment]
This issue is caused by the fact that we install the pack CLI from the pack image. Evidence of this can be seen by running:
```
docker run buildpacksio/pack:0.14.0 -- version
#{PACK_VERSION}#
```
which gets the version of the pack CLI baked into the image.
