### ISSUE TITLE
Application image labels too long for containerd

### ISSUE THREAD

**Issue by jimmykarily** [paketo-buildpacks/full-builder#415]
## What happened?

I'm building an image using the full-builder. I'm doing this through [Epinio](https://github.com/epinio/epinio/). The cluster I'm using is [k3d](https://k3d.io/v5.0.0/) using the image `rancher/k3s:v1.22.2-k3s2`. That image is running containerd `v1.5.7` in it.

When containerd tries to start a container using the `paketobuildpacks/builder:full` image, it fails with an error:

```
label key and value greater than maximum size (4096 bytes), key: io.buildpa: invalid argument 
```

This seems to originate here: https://github.com/jessvalarezo/containerd/blob/18c4322bb3ddcb8f8b4eea2f3c027a06194041b4/labels/validate.go

Everything works fine on containerd `v1.4.11`. I had a look at changelogs and I think it's this one (introduced in [1.5.6](https://github.com/containerd/containerd/releases/tag/v1.5.6)):

https://github.com/containerd/containerd/issues/5938
https://github.com/containerd/containerd/pull/6012/files

Is there any reason we we have such long labels on the image?
There have been similar issues in the past: https://github.com/paketo-buildpacks/full-builder/issues/191

* What were you attempting to do?

Create a container from `paketobuildpacks/builder:full` with containerd 1.5.6

* What did you expect to happen?

the container to be started

* What was the actual behavior? Please provide log output, if possible.

See description. Original issue started here: https://github.com/epinio/epinio/issues/833#issuecomment-937837491

## Build Configuration

* What platform (`pack`, `kpack`, `tekton` buildpacks plugin, etc.) are you
  using? Please include a version.

Epinio build from here: https://github.com/epinio/epinio/pull/868

* What buildpacks are you using? Please include versions.

Didn't get that far

* What builder are you using? If custom, can you provide the output from `pack
  inspect-builder <builder>`?

paketobuildpacks/builder:full (sha256:e68c940932d2cf17ec10dbc9a4de7af08deec728d7cf5de9278803ec0f96ba6e)

## Checklist

* [x] I have included log output.
* [x] The log output includes an error message.
* [x] I have included steps for reproduction. (kinda)

**Comment by ForestEckhardt** [comment]
@jimmykarily Hey there, just doing a quick bump. Is this still and issue that you are running into?

**Comment by jimmykarily** [comment]
@ForestEckhardt it's fixed. I'm closing this, thanks.
