### ISSUE TITLE
ERROR: failed to build: validating stack mixins...

### ISSUE THREAD

**Issue by meip** [paketo-buildpacks/full-builder#709]
## Current Behavior

We're using the latest images from gcr.io: gcr.io/paketo-buildpacks/run:full-cnb

```
ERROR: failed to build: validating stack mixins: 'gcr.io/paketo-buildpacks/run:full-cnb' missing required mixin(s): PyYAML, argparse, bigdecimal, bzr, cmath, configobj, csv, date, dbm, did_you_mean, etc, fcntl, fiddle, fileutils, gdbm, io-console, ipaddr, json, minitest, net-telnet, netifaces, power_assert, psych, python-apt, rdoc, scanf, sdbm, six, stringio, strscan, test-unit, webrick, wsgiref, zlib
```

I assume this commit causes the issue: https://github.com/paketo-buildpacks/full-builder/pull/705

## Possible Solution

Pin back to an older version, like the one from two days ago: 

```
gcr.io/paketo-buildpacks/builder@sha256:60361e519fc37c19420575b93d82a5ab0b445320b2d535c9a7c1ae3e322b473d
```

**Comment by sophiewigmore** [comment]
@meip thank you for surfacing this. We updated the way we create images and push them, and it appears the GCR mirror in the builder was not updated. I'll get a fix out!

**Comment by sophiewigmore** [comment]
@meip will you try it now and let me know if you're still running into the same problem?
